<a href="https://colab.research.google.com/github/juanepstein99/DI_Bootcamp/blob/main/Week10/Day2/ExercisesXP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**🌟 Exercise 1 : Array Creation and Manipulation**

Instructions:

Create a 1D NumPy array containing numbers from 0 to 9.

In [1]:
import numpy as np

arr = np.arange(0, 10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


**🌟 Exercise 2 : Type Conversion and Array Operations**

Instructions:

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [2]:
lst = [3.14, 2.17, 0, 1, 2]

arr = np.array(lst)
arr_int = arr.astype(int)

print(arr_int)

[3 2 0 1 2]


**🌟 Exercise 3 : Working with Multi-Dimensional Arrays**

Instructions:

Create a 3x3 NumPy array with values ranging from 1 to 9.

In [3]:
arr = np.arange(1, 10).reshape(3, 3)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers**

Instructions:

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [4]:
arr = np.random.rand(4, 5)

print(arr)

[[0.26846497 0.2408712  0.17069698 0.76782835 0.03122751]
 [0.25813897 0.83769413 0.37514003 0.59668027 0.35090386]
 [0.36747221 0.20241028 0.94266803 0.82048487 0.68642099]
 [0.41117574 0.85401947 0.01261047 0.78503695 0.08057002]]


**🌟 Exercise 5 : Indexing Arrays**

Instructions:

Select the second row from a given 2D NumPy array.

In [5]:
array = np.array([[21,22,23,22,22],
                  [20,21,22,23,24],
                  [21,22,23,22,22]])

second_row = array[1]

print(second_row)

[20 21 22 23 24]


**🌟 Exercise 6 : Reversing elements**

Instructions:

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [6]:
arr = np.arange(10)

reversed_arr = arr[::-1]

print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


**🌟 Exercise 7 : Identity Matrix**

Instructions:

Create a 4x4 identity matrix using NumPy.

In [7]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**🌟 Exercise 8 : Simple Aggregate Funcs**

Instructions:

Find the sum and average of a given 1D array.

In [8]:
total_sum = np.sum(arr)
average = np.mean(arr)

print(f"Sum: {total_sum}, Average: {average}")

Sum: 45, Average: 4.5


**🌟 Exercise 9 : Create Array and Change its Structure**

Instructions:

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [9]:
arr = np.arange(1, 21).reshape(4, 5)

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**🌟 Exercise 10 : Conditional Selection of Values**

Instructions:

Extract all odd numbers from a given NumPy array.

In [11]:
arr = np.arange(10)

odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
